### ISSUE TITLE
Correct setting for motion_strength in the pipeline

### ISSUE THREAD

**Issue by ywangsherry** [alibaba/animate-anything#66]
- In app.py, motion_strength uses motion_scale * mask.mean().item(). https://github.com/alibaba/animate-anything/blob/2b451733a31856745e4ce91a635de349eab25503/app.py#L97-L110
- In train.py, motion_strength uses the motion_scale input directly. https://github.com/alibaba/animate-anything/blob/ab3c23b33df53ae83d8fb1c708db7de79ab67cdb/train.py#L765-L777

If motion_scale is 5, in app.py, the pipeline uses 5 * mask.mean().item(), while in train.py, it uses 5.[ The pipeline’s parameter documentation does](https://github.com/alibaba/animate-anything/blob/070574cc6661f80d51580da766486163ebc18446/models/pipeline.py#L12-L97) not specify details about `motion`. Therefore, I’m a bit confused about which one is correct, app.py or train.py?

**Comment by sculmh** [comment]
Theoretically, we should directly use motion_strength. Multiplying it by mask.mean() serves to reduce the motion_strength because the value range of the mask is between [0,1]. For the same motion_strength, if the mask drawn has a very small movable area, it would lead to a tendency to exhibit very large motion amplitudes, which easily causes deformation. Therefore, the developer who wrote app.py scaled the motion_strength based on the size of the mask area.
